language: bash
dist: xenial
sudo: required

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: y
    - SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: y

addons:
  snaps:
  - name: snapcraft
    channel: stable
    classic: true
  - name: lxd
    channel: stable

before_install:
  - sudo apt-get update
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto

script:
  - sudo snapcraft --use-lxd

after_success:
  - sudo snap install *.snap --dangerous

after_failure:
  - sudo journalctl -u snapd
  # - http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
