name: grafana
version: 6.7.2
summary: feature rich metrics dashboard and graph editor
base: core18
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Cloudwatch,
  Elasticsearch, Graphite, InfluxDB, OpenTSB, Prometheus, and Hosted Metrics.
confinement: strict
grade: stable

apps:
  grafana:
    command: 'bin/grafana.wrapper'
    plugs: [network-bind, network]
    daemon: simple

  grafana-cli:
    command: 'bin/grafana-cli.wrapper'
    plugs: [network-bind, network]

parts:
  snap-wrappers:
    plugin: dump
    source: bin
    organize:
      grafana.wrapper: bin/grafana.wrapper
      grafana-cli.wrapper: bin/grafana-cli.wrapper
  grafana:
    plugin: go
    source: https://github.com/grafana/grafana.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    source-depth: 1
    go-importpath: github.com/grafana/grafana
    build-packages: [build-essential, g++]
    stage-packages: [libfontconfig1, libfreetype6]
    override-build: |
        mkdir ${SNAPCRAFT_PART_INSTALL}/bin ${SNAPCRAFT_PART_INSTALL}/conf
        cd ${SNAPCRAFT_PART_BUILD}
        go run build.go setup
        go run build.go build
        cp -p ${SNAPCRAFT_PART_BUILD}/bin/*/grafana-server \
          ${SNAPCRAFT_PART_BUILD}/bin/*/grafana-cli \
          ${SNAPCRAFT_PART_INSTALL}/bin/
        cp -p ${SNAPCRAFT_PART_BUILD}/conf/defaults.ini ${SNAPCRAFT_PART_INSTALL}/conf/
  grafana-ui:
    after: [grafana]
    plugin: nodejs
    source-type: git
    source: https://github.com/grafana/grafana.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    nodejs-version: '12.16.2'
    nodejs-package-manager: yarn
    override-build: |
      export PATH=${SNAPCRAFT_PART_BUILD}/../npm/bin:$PATH
      yarn upgrade
      # on arm, s390x, and ppc systems remove phantomjs as required from the
      # package.json and yarn lock as it's not available from npm on those
      # architectures
      ARCH=$(uname -m)
      case $ARCH in
      aarch64|arm*|s390*|ppc*)
        yarn remove phantomjs-prebuilt --ignore-workspace-root-check;;
      esac
      yarn install --pure-lockfile
      ${SNAPCRAFT_PART_BUILD}/node_modules/.bin/grunt build --force
      cp -rf public ${SNAPCRAFT_PART_INSTALL}/public
