name: grafana
version: 7.2.0
summary: feature rich metrics dashboard and graph editor
base: core20
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Cloudwatch,
  Elasticsearch, Graphite, InfluxDB, OpenTSB, Prometheus, and Hosted Metrics.
confinement: strict
grade: stable
architectures:
  - build-on: s390x
  - build-on: ppc64el
  - build-on: arm64
  - build-on: amd64

apps:
  grafana:
    command: 'bin/grafana.wrapper'
    plugs: [network-bind, network]
    daemon: simple

  grafana-cli:
    command: 'bin/grafana-cli.wrapper'
    plugs: [network-bind, network]

parts:
  snap-wrappers:
    plugin: dump
    source: bin
    organize:
      grafana.wrapper: bin/grafana.wrapper
      grafana-cli.wrapper: bin/grafana-cli.wrapper
  grafana:
    plugin: go
    source: https://github.com/grafana/grafana.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    source-depth: 1
    build-packages: [build-essential, g++]
    stage-packages: [libfontconfig1, libfreetype6]
    override-build: |
        set -x
        snapcraftctl build
        mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin ${SNAPCRAFT_PART_INSTALL}/conf
        cd ${SNAPCRAFT_PART_BUILD}
        GO111MODULE=on go run build.go setup
        GO111MODULE=on go run build.go build
        cp -p ${SNAPCRAFT_PART_BUILD}/bin/*/grafana-server \
          ${SNAPCRAFT_PART_BUILD}/bin/*/grafana-cli \
          ${SNAPCRAFT_PART_INSTALL}/bin/
        cp -p ${SNAPCRAFT_PART_BUILD}/conf/defaults.ini ${SNAPCRAFT_PART_INSTALL}/conf/
  grafana-ui:
    after: [grafana]
    plugin: npm
    source-type: git
    source: https://github.com/grafana/grafana.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    nodejs-version: '12.18.0'
    build-packages: [python2-minimal,python2-dev]
    override-build: |
      set -x
      # https://forum.snapcraft.io/t/issue-with-nodejs-plugin-when-using-base-keyword/11109/8
      echo "unsafe-perm = true" > ~/.npmrc
      snapcraftctl build
      export PYTHON=/usr/bin/python2
      # XXX check if needed
      PATH="$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin:$SNAPCRAFT_PART_INSTALL/bin"
      NODE_ENV="production"
      npm install -g --prefix $SNAPCRAFT_PART_INSTALL yarn
      yarn install --pure-lockfile --no-progress
      ${SNAPCRAFT_PART_BUILD}/node_modules/.bin/grunt build
      cp -rf public ${SNAPCRAFT_PART_INSTALL}/public
      cp -rf tools ${SNAPCRAFT_PART_INSTALL}/tools
